embark/embark/urls.py
__copyright__ = 'Copyright 2021-2025 Siemens Energy AG, Copyright 2021-2025 The AMOS Projects'
__author__ = 'm-1-k-3, RaviChandra, Garima Chauhan, Maximilian Wagner, diegiesskanne, ashiven'
__license__ = 'MIT'

from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('updater.urls')),
    path('', include('uploader.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls')),
    path('', include('reporter.urls')),
    path('', include('tracker.urls')),
    path('', include('porter.urls')),
    path('', include('workers.urls')),
    path('', include('settings.urls')),
] + staticfiles_urlpatterns()

embark/uploader/urls.py
__copyright__ = 'Copyright 2021-2025 Siemens Energy AG, Copyright 2021 The AMOS Projects, Copyright 2021 Siemens AG'
__author__ = 'Benedikt Kuehne, Maximilian Wagner, p4cx, Ashutosh Singh, VAISHNAVI UMESH, diegiesskanne, uk61elac, RaviChandra, Vaish1795, Garima Chauhan, m-1-k-3, SirGankalot, ClProsser'
__license__ = 'MIT'

from django.urls import path
from uploader import views
from .views import UploaderView

# view routing
urlpatterns = [

    path('uploader/', views.uploader_home, name='embark-uploader-home'),

    path('api/uploader/', UploaderView.as_view()),

    path('uploader/manage/', views.manage_file, name='embark-uploader-manage-file'),
    path('uploader/save/', views.save_file, name='embark-uploader-save'),
    path('uploader/delete/', views.delete_fw_file, name='embark-uploader-delete'),
    path('uploader/download/', views.download_firmware, name='embark-uploader-download'),

    path('uploader/start/', views.start_analysis, name='embark-uploader-start-analysis'),

    path('uploader/device/', views.device_setup, name='embark-uploader-device'),
    path('uploader/vendor/', views.vendor, name='embark-uploader-vendor'),
    path('uploader/label/', views.label, name='embark-uploader-label'),

    path('uploader-minimal/', views.uploader_home_minimal, name='embark-uploader-home-minimal'),
]

embark/users/urls.py
__copyright__ = 'Copyright 2021-2025 Siemens Energy AG, Copyright 2021-2025 The AMOS Projects, Copyright 2021 Siemens AG'
__author__ = 'Garima Chauhan, YulianaPoliakova, Benedikt Kuehne, VAISHNAVI UMESH, p4cx, m-1-k-3, ashiven'
__license__ = 'MIT'

from django.conf import settings
from django.urls import path

from users import views


urlpatterns = [
    path(settings.LOGIN_URL, views.embark_login, name='embark-login'),
    path('user/', views.user_main, name='embark-user-main'),
    path('user/register/', views.register, name='embark-register'),
    path('user/activate/<int:user_id>/<str:token>/', views.activate, name='embark-activate-user'),
    path('user/reset_password/', views.reset_password, name='embark-password-reset'),
    path(settings.LOGOUT_REDIRECT_URL, views.embark_logout, name='embark-logout'),
    path('user/password_change/', views.password_change, name='embark-password-change'),
    path('user/delete/', views.acc_delete, name='embark-acc-delete'),
    path('user/<int:user_id>/deactivate', views.deactivate, name='embark-deactivate-user'),
    path('user/set_timezone/', views.set_timezone, name='embark-acc-timezone'),
    path("user/generate_api_key/", views.generate_api_key, name="embark-acc-apikey"),
    path("user/api_test/", views.api_test, name="embark-api-test"),
    path('log/<int:log_type>/<int:lines>/', views.get_log, name='log'),     # TODO move to admin
]

embark/users/models.py
__copyright__ = 'Copyright 2021-2025 Siemens Energy AG, Copyright 2021-2025 The AMOS Projects'
__author__ = 'Garima Chauhan, m-1-k-3, Benedikt Kuehne, ashiven, SirGankalot'
__license__ = 'MIT'

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Team(models.Model):
    name = models.CharField(primary_key=True, verbose_name="name", max_length=150, unique=True)
    is_active = models.BooleanField(default=True, help_text='Whether this Team is active or not')
    created = models.DateTimeField(auto_now_add=True, help_text='Date time when this entry was created')
    modified = models.DateTimeField(auto_now=True, help_text='Date time when this entry was modified')


class User(AbstractUser):
    timezone = models.CharField(max_length=32, choices=settings.TIMEZONES, default='UTC')
    email = models.EmailField(verbose_name="email address", blank=True, unique=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, editable=True, related_name='member_of_team')
    is_active_member = models.BooleanField(default=True, help_text='Whether this team member is active or not')
    api_key = models.CharField(max_length=64, blank=True, null=True, help_text="API key of the user")

    class Meta:
        default_permissions = ()    # disable "add", "change", "delete" and "view" default permissions
        permissions = (
            ("user_permission", "Can access user menues of embark"),
            ("tracker_permission", "Can access tracker functionalities of embark"),
            ("updater_permission", "Can access updater functionalities of embark"),
            ("uploader_permission_minimal", "Can access uploader functionalities of embark"),
            ("uploader_permission_advanced", "Can access all uploader functionalities of embark"),
            ("porter_permission", "Can access porter functionalities of embark"),
            ("reporter_permission", "Can access reporter functionalities of embark"),
            ("dashboard_permission_minimal", "Can access dashboard functionalities of embark"),
            ("dashboard_permission_advanced", "Can access all dashboard functionalities of embark"),
            ("worker_permission", "Can access worker functionalities of embark"),
            ("settings_permission", "Can access settings functionalities of embark")
        )

embark/users/views.py
# pylint: disable=R1705
__copyright__ = 'Copyright 2021-2025 Siemens Energy AG, Copyright 2021-2025 The AMOS Projects, Copyright 2021 Siemens AG'
__author__ = 'YulianaPoliakova, Garima Chauhan, p4cx, Benedikt Kuehne, VAISHNAVI UMESH, m-1-k-3, ashiven, SirGankalot, ClProsser'
__license__ = 'MIT'

import builtins
import logging
import secrets

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import Permission, Group
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.forms import ValidationError
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.core.mail import send_mail
from django.db.models import Q
from django.http import JsonResponse

from users.forms import LoginForm, SignUpForm, ResetForm
from users.models import User
from users.decorators import require_api_key

logger = logging.getLogger(__name__)


@permission_required("users.user_permission", login_url='/')
@require_http_methods(["GET"])
def user_main(request):
    user = get_user(request)
    logger.debug("Account settings for %s", user)
    #   return render(request, 'user/index.html', {"timezones": settings.TIMEZONES, "server_tz": settings.TIME_ZONE, 'user': user})
    return render(request, 'user/index.html', {"timezones": settings.TIMEZONES, "server_tz": settings.TIME_ZONE})


@csrf_exempt
@require_http_methods(["GET", "POST"])
def register(request):
    if request.method == "POST":
        logger.debug(request.POST)
        try:
            user = get_user(request)
            signup_form = SignUpForm(data=request.POST)
            if signup_form.is_valid():
                username = signup_form.cleaned_data.get('username')
                password = signup_form.cleaned_data.get('password2')
                email = signup_form.cleaned_data.get('email')
                user = User.objects.create(username=username, email=email)
                user.set_password(password)
                user.is_active = False
                if Group.objects.get(name='New_User'):
                    user.groups.add(Group.objects.get(name='New_User'))
                user.save()
                logger.debug('User created')
                token = default_token_generator.make_token(user)
                current_site = get_current_site(request)
                mail_subject = 'Activate your EMBArk account.'
                message = render_to_string('user/email_template_activation.html', context={
                    'username': user.username,
                    'domain': current_site.domain,
                    'uid': user.id,
                    'token': token,
                })
                if settings.EMAIL_ACTIVE is True:
                    send_mail(mail_subject, message, 'system@' + settings.DOMAIN, [email])
                    messages.success(request, 'Registration successful. Please check your email to activate')
                    return redirect(reverse('embark-login'))
                else:
                    logger.debug("Registered, redirecting to login")
                    if activate_user(user, token):
                        messages.success(request, 'Registration successful.')
                        return redirect(reverse('embark-login'))
                    else:
                        raise ValidationError("Activation Error")
        except builtins.Exception as error:
            logger.exception('Wide exception in Signup: %s', error)
            messages.error(request, 'Something went wrong when signing up the user.')
    else:
        signup_form = SignUpForm()
    return render(request, 'user/register.html', {'form': signup_form})


@require_http_methods(["GET", "POST"])
def embark_login(request):
    """
    Login handled via POST
    """
    if request.method == "POST":
        try:
            login_form = LoginForm(request=request, data=request.POST)
            logger.debug(login_form)
            if login_form.is_valid():
                logger.debug('form valid')
                user = login_form.get_user()
                if user:
                    logger.debug('User authenticated')
                    login(request, user)
                    logger.debug('User logged in')
                    request.session["django_timezone"] = user.timezone
                    # messages.success(request, str(user.username) + ' timezone set to : ' + str(user.timezone))
                    return redirect('embark-uploader-home')
                logger.debug('User could not be authenticated - backend error?')
                messages.error(request, 'User could not be authenticated at this time')
                return redirect('embark-login')
            logger.debug('Form errors: %s', login_form.errors.as_text())
            return render(request, 'user/login.html', {'form': login_form})
        except ValidationError as valid_error:
            logger.error("Exception in value: %s ", valid_error)
            messages.error(request, 'User is deactivated')
            return redirect('embark-login')
        except builtins.Exception as error:
            logger.exception('Wide exception in Signup: %s', error)
            messages.error(request, 'Something went wrong when logging in the user.')
            return redirect('embark-login')
    login_form = LoginForm()
    return render(request, 'user/login.html', {'form': login_form})


@login_required(login_url='/' + settings.LOGIN_URL)
def embark_logout(request):
    logout(request=request)
    logger.debug("Logout user %s", request)
    messages.success(request, 'Logout successful.')
    return redirect('embark-login')


@login_required(login_url='/' + settings.LOGIN_URL)
@require_http_methods(["GET", "POST"])
def password_change(request):   # TODO adapt t
    if request.method == "POST":
        logger.debug(request.POST)
        user = get_user(request)

        data = {k: v[0] for k, v in dict(request.POST).items()}
        logger.debug(data)
        try:
            body = {k: v[0] for k, v in dict(request.POST).items()}
            try:
                old_password = body['oldPassword']
                new_password = body['newPassword']
                confirm_password = body['confirmPassword']

                if user.check_password(old_password):
                    if old_password == new_password:
                        logger.debug('New password = old password')
                        messages.error(request, 'New password matches the old password')
                        return render(request, 'user/passwordChange.html')
                    if new_password == confirm_password:
                        user.set_password(new_password)
                        user.save()
                        authenticate(request, username=user.username, password=new_password)
                        login(request, user)
                        logger.debug('New password set, user authenticated')
                        messages.success(request, 'Password change successful.')
                        return render(request, 'user/passwordChangeDone.html')
                    else:
                        logger.debug('Passwords do not match')
                        messages.error(request, 'Passwords do not match.')
                        return render(request, 'user/passwordChange.html')
                else:
                    logger.debug('Old password is incorrect')
                    messages.error(request, 'Old password is incorrect.')
                    return render(request, 'user/passwordChange.html')
            except KeyError:
                logger.exception('Missing keys from data-passwords')
                messages.error(request, 'Some fields are empty!')
                return render(request, 'user/passwordChange.html')
        except builtins.Exception as error:
            logger.exception('Wide exception in Password Change: %s', error)
            messages.error(request, 'Something went wrong when changing the password for the user.')
            return render(request, 'user/passwordChange.html')
    return render(request, 'user/passwordChange.html')


@csrf_exempt
@login_required(login_url='/' + settings.LOGIN_URL)
@require_http_methods(["GET", "POST"])
def acc_delete(request):
    if request.method == "POST":
        logger.debug('disabling account')
        user = get_user(request)
        email = user.email
        token = default_token_generator.make_token(user)
        current_site = get_current_site(request)
        mail_subject = 'Delete your EMBArk account.'
        message = render_to_string('user/email_template_deactivation.html', context={
            'user': user,
            'username': user.username,
            'domain': current_site.domain,
            'uid': user.id,
            'token': token,
        })
        if settings.EMAIL_ACTIVE is True:
            send_mail(mail_subject, message, 'system@' + settings.DOMAIN, [email])
            messages.success(request, 'Please check your email to confirm deletion')
            return redirect(reverse('embark-deactivate-user', kwargs={'uuid': user.id}))
        else:
            logger.debug(' %s Account: %s disabled', timezone.now().strftime("%H:%M:%S"), user)
            user.username = user.get_username() + '_disactivated_' + timezone.now().strftime(
                "%H:%M:%S")     # workaround for not duplicating entry users_user.username
            user.is_active = False
            user.save()
            messages.success(request, 'Account successfully deleted.')

embark/templates/user/accountDelete.html
{% extends "base.html" %}
{% block title %} Delete Account {% endblock title %}
{% load static %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'content/css/passwordReset.css' %}"/>{% endblock style %}
{% block navigation %}{% include "navigation.html" %}{% endblock navigation %}
{% block maincontent %}

<div class="auth-wrapper">
    <form action="{% url 'embark-acc-delete' %}" method="post" novalidate>
        <div class="box box-primary">
                <div class="box-header">
                <h2 class="page-header"><i class="fa fa-lock"></i> Permanently delete my Account </h2>
            </div>
            <div class="box box-body-second">
                <p>Are you sure you want to permanently delete your account?</p>
            </div>
            <div class="btn-cnt">
                <p>
                    <button class="btn-reset" type="submit" name="DeleteAcc">Delete Account</button>
                </p>
            </div>
        </div>
    </form>
</div>

{% endblock maincontent %}

embark/templates/user/activate.html
{% csrf_token %}
{% for field in form %}
<label >{{ field.label_tag }}</label>
{{ field }}
{% endfor %}

embark/templates/user/apiKeyGen.html
{% load static %}
{% block style %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'content/css/apiKeyGen.css' %}" />
{% endblock style %}
{% block maincontent %}
<div class="apikey-container">
  <form action="{% url 'embark-acc-apikey' %}" method="get">
    {% csrf_token %}
    <label for="apikey-textbox">API Key:</label>
    <div class="apikey-textbox-row">
      <input type="text" id="apikey-textbox" name="apikey" value="" readonly />
      <input type="button" id="btn-copy" class="solid btn-copy" value="Copy" onclick="copyToClipboard()" />
    </div>
    <input type="submit" class="solid btn-generate" value="Generate" />
  </form>

<!-- Hidden place to render Django messages -->
<div class="django-messages">
  {% for message in messages %}
  <div class="django-message">
    {{ message }}
  </div>
  {% endfor %}
</div>

<script>
    function extractApiKey() {
      let messages = document.getElementsByClassName('django-message');
      for (let i = 0; i < messages.length; i++) {
        let text = messages[i].innerText || messages[i].textContent;
        if (text.trim().startsWith('Your new API key:')) {
          let apiKey = text.replace('Your new API key:', '').trim();
          document.getElementById('apikey-textbox').value = apiKey;
          break;
        }
      }
    }

    function copyToClipboard() {
      let textbox = document.getElementById("apikey-textbox");
      if (!textbox.value) {
	      alert("Error, please generate a key first.");
	      return;
      }
      textbox.select();
      document.execCommand("copy");
      document.getElementById("btn-copy").value = "Copied!";
    }

    window.onload = extractApiKey;
</script>
</div>
{% endblock maincontent %}

embark/templates/user/email_template.html
{% autoescape off %}
Dear {{ username }},

Please follow the link to confirm your registration,
http://{{ domain }}{% url 'activate' user_id=uid activation_token=token %}

OR manually input the following token: {{ token }}
{% endautoescape %}

embark/templates/user/email_template_activation.html
{% autoescape off %}
Dear {{ username }},

Please follow the link to confirm your registration,
http://{{ domain }}{% url 'embark-activate-user' user_id=uid token=token %}

OR manually input the following token: {{ token }}
{% endautoescape %}

embark/templates/user/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'content/css/menu.css' %}"/>{% endblock style %}
{% block title %}EMBArk User-menue{% endblock title %}

{% block navigation %}{% include "navigation.html" %}{% endblock navigation %}
{% block maincontent %}
{% if user.is_staff or user.is_superuser %}
<div class="d-flex justify-content-center">
    <h3><span class="badge bg-secondary"><a href="{% url 'admin:index' %}">
        <input class="solid btn-login" type="submit" value="Admin-page" />
    </a></span></h3>

</div>
{% endif %}
    <div class="container-fluid">
        {% block timezone %}{% include "user/timezone.html" %}{% endblock timezone %}
    </div>
    <div class="container-fluid">
  	{% block apikey %}{% include "user/apiKeyGen.html" %}{% endblock apikey %}
    </div>
{% endblock maincontent %}

embark/templates/user/log.html
{% extends "base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'content/css/log.css' %}"/>{% endblock style %}
{% block title %}EMBArk log{% endblock title %}
{% block navigation %}{% include "navigation.html" %}{% endblock navigation %}
{% block maincontent %}
    <div id="logHeader"><strong>{{ header }}</strong></div>
    <div id="logBox">
    {{ log }}
    </div>
{% endblock maincontent %}

embark/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'content/css/login.css' %}"/>{% endblock style %}
{% block title %}EMBArk login{% endblock title %}
{% block maincontent %}
    <div class="login-form-container">
        <div id="embarkLogo">
          <img src="{% static 'content/images/embark_logo.svg' %}" alt="EMBArk logo graphic" height="auto" width="auto"/>
        </div>
        <div class="d-flex justify-content-center">
            <!--  TODO put actual version here-->
            <h2><span class="badge bg-primary">New</span>  Version 0.3</h2>
        </div>
        <div class="d-flex justify-content-center">
          <h3><span class="badge bg-secondary">New</span> Orchestrator Integration </h3>
        </div>
        <div class="login">
            <form action="{% url 'embark-login' %}" class="login-form" method="post" novalidate>
                <h2 class="title">Sign in</h2>
                {% csrf_token %}
                {% if form.errors %}
                    <ul>
                    {% for field, error_list in form.errors.items %}
                        <li><span class="badge bg-danger">{{ error_list|join:", " }}</span></li>
                    {% endfor %}
                    </ul>
                {% endif %}
                {% for field in form %}
                    {% bootstrap_field field %}
                {% endfor %}

                <input id="loginButton" type="submit" class="solid btn-login" value="login" />
            </form> 
        </div>
        <div id="login_footer">
            <a href="{% url 'embark-password-reset' %}">
                <input class="solid btn-login" type="submit" value="Lost Password?" />
            </a>
            <a href="{% url 'embark-register' %}">
                <input class="solid btn-login" type="submit" value="Register" />
            </a>
        </div>

    </div>
{% endblock maincontent %}

embark/templates/user/lostPassword.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'content/css/passwordReset.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'content/css/login.css' %}"/>
{% endblock style %}
{% block title %}Reset Lost Password{% endblock title %}
{% block maincontent %}
    <div class="password-change-container">
        {% if email_setting %}
            <div class="reset">
                <form action="{% url 'embark-password-reset' %}" class="password-reset-form" method="post" novalidate>
                    <h2 class="title">Reset Password</h2>
                    {% csrf_token %}
                    {% for field in form %}
                        {% bootstrap_field field %}
                    {% endfor %}
                    <input id="loginButton" type="submit" class="solid btn-reset" value="reset" />
                </form> 
                <div id="login_footer">
                    <a href="{% url 'embark-login' %}">
                        <input class="solid btn-login" type="submit" value="Login" />
                    </a>
                </div>
            </div>
        {% else %}
            <div class="d-flex justify-content-center">
                <h1>
                    Contact your Admin
                    {{ admin_email }}
                </h1>
            </div>
        {% endif %}
    </div>
{% endblock maincontent %}

embark/templates/user/menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %} EMBArk User-menu {% endblock title %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'content/css/menu.css' %}"/>{% endblock style %}
{% block navigation %}{% include "navigation.html" %}{% endblock navigation %}
{% block maincontent %}
<!--TODO make work-->
<!--
    <div class="container-fluid">
      <div class="card card-outline card-primary">
        <div class="card-header">
          <h3 class="card-title">{{ userList.count }} Users</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <table id="userlist" class="table table-bordered table-hover">
              <thead>
                  <tr>
                      <th style="width: 15%">
                          User
                      </th>
                      <th style="width: 20%">
                          Email
                      </th>
                      <th style="width: 5%">
                          Active
                      </th>
                      <th style="width: 10%">
                          Group
                      </th>
                      <th style="width: 5%">
                          Admin
                      </th>
                      <th style="width: 20%" class="text-center">
                          Actions
                      </th>
                  </tr>
              </thead>
              <tbody>

                {% for group in group_list %}

                  {% for user in group.user_set.all %}

                    <tr>
                      <td>
                        {{ user.username }}
                      </td>
                      <td>
                        {{ user.email }}
                      </td>
                      <td class="text-center">
                        {% if user.is_active %}
                            <i class="fas fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fas fa-times-circle text-danger"></i>
                        {% endif %}
                      </td>
                      <td class="text-center">
                        {{ group }}
                      </td>
                      <td class="text-center">
                        {% if user.is_superuser %}
                            <i class="fas fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fas fa-times-circle text-danger"></i>
                        {% endif %}
                      </td>

                      <td class="project-actions text-center">
                          <a class="btn btn-primary btn-sm" href="/admin/auth/user/">
                              <i class="fas fa-folder"></i>
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="/user/edit/{{ user.pk }}">
                              <i class="fas fa-pencil-alt"></i>
                              Edit
                          </a>

                          <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".mm-modal-{{user.pk}}">
                            <i class="fas fa-trash"></i>
                              Delete
                          </button>

                      </td>

                    </tr>

                      <div class="modal modal-danger fade mm-modal-{{ user.pk }}" id="modal-danger">
                        <div class="modal-dialog">
                          <div class="modal-content bg-danger">
                            <div class="modal-header">
                              <h4 class="modal-title">Are you sure?</h4>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <p>Delete User&hellip;</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                              <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                              <button type="button" onclick="DeleteID({{ user.pk }});" class="btn btn-outline-light">Delete user</button>
                            </div>
                          </div>
                        </div>
                      </div>



                  {% endfor %}

              {% endfor %}

              </tbody>
          </table>
        </div>
       
      </div>
      
    </div>

-->
{% endblock maincontent %}

{% block javascripts %}
<script>
  $(function () {
    $("#userlist").DataTable({
      "paging": true,
      "searching": true,
      "responsive": true, 
      "lengthChange": false, 
      "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#userlist_wrapper .col-md-6:eq(0)');
  });
</script>

<script>
  function DeleteID(del_id) {
        $.ajax({
            type: 'POST',
            url: "/configuration/user/delete/",
            headers:{
              "X-CSRFToken": '{{ csrf_token }}'
            },
            data : { 'delete_id': del_id},

            success : function(json) {
              document.location.href = "/user/"; 
            }
        })
  }
</script>

{% endblock javascripts %}

embark/templates/user/passwordChangeDone.html
{% extends "base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'content/css/passwordReset.css' %}"/>{% endblock style %}
{% block navigation %}{% include "navigation.html" %}{% endblock navigation %}
{% block maincontent %}
    <div class="box box-primary">
    <h2> Password successfully changed! </h2>
        <div class="btn-cnt">
        <a href="{% url 'embark-MainDashboard' %}">
            <input class="btn-reset" type="submit" value="Back to dashboard" />
        </a>
        </div>
    </div>
{% endblock maincontent %}

embark/templates/user/timezone.html
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<div class="d-flex justify-content-center">
    <h3><span class="badge bg-secondary">The servers timezone is: {{ server_tz }}</span></h3>
</div>
<form action="{% url 'embark-acc-timezone' %}" method="post">
    {% csrf_token %}
    <label for="timezone">Time zone:</label>
    <select name="timezone">
        {% for value,tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Set">
</form>